# frozen_string_literal: true

require_relative 'attractor/version'
require_relative 'attractor/errors'

# Layer 1: Unified LLM Client
require_relative 'attractor/llm/usage'
require_relative 'attractor/llm/finish_reason'
require_relative 'attractor/llm/content_part'
require_relative 'attractor/llm/message'
require_relative 'attractor/llm/tool'
require_relative 'attractor/llm/tool_call'
require_relative 'attractor/llm/tool_result'
require_relative 'attractor/llm/request'
require_relative 'attractor/llm/response'
require_relative 'attractor/llm/stream_event'
require_relative 'attractor/llm/stream_accumulator'
require_relative 'attractor/llm/retry_policy'
require_relative 'attractor/llm/model_catalog'
require_relative 'attractor/llm/sse_parser'
require_relative 'attractor/llm/providers/base_adapter'
require_relative 'attractor/llm/providers/anthropic_adapter'
require_relative 'attractor/llm/providers/openai_adapter'
require_relative 'attractor/llm/providers/gemini_adapter'
require_relative 'attractor/llm/client'
require_relative 'attractor/llm/generate'

# Layer 2: Coding Agent Loop
require_relative 'attractor/agent/execution_env/base'
require_relative 'attractor/agent/execution_env/local'
require_relative 'attractor/agent/execution_env/sprite'
require_relative 'attractor/agent/truncation'
require_relative 'attractor/agent/tools/tool_registry'
require_relative 'attractor/agent/tools/read_file'
require_relative 'attractor/agent/tools/write_file'
require_relative 'attractor/agent/tools/edit_file'
require_relative 'attractor/agent/tools/shell'
require_relative 'attractor/agent/tools/grep_tool'
require_relative 'attractor/agent/tools/glob_tool'
require_relative 'attractor/agent/tools/apply_patch'
require_relative 'attractor/agent/tools/spawn_agent'
require_relative 'attractor/agent/turn'
require_relative 'attractor/agent/events'
require_relative 'attractor/agent/event_emitter'
require_relative 'attractor/agent/loop_detector'
require_relative 'attractor/agent/session_config'
require_relative 'attractor/agent/system_prompt_builder'
require_relative 'attractor/agent/provider_profiles/base_profile'
require_relative 'attractor/agent/provider_profiles/anthropic_profile'
require_relative 'attractor/agent/provider_profiles/openai_profile'
require_relative 'attractor/agent/provider_profiles/gemini_profile'
require_relative 'attractor/agent/subagent'
require_relative 'attractor/agent/session'

# Layer 3: Attractor Pipeline Runner
require_relative 'attractor/pipeline/node'
require_relative 'attractor/pipeline/edge'
require_relative 'attractor/pipeline/graph'
require_relative 'attractor/pipeline/lexer'
require_relative 'attractor/pipeline/parser'
require_relative 'attractor/pipeline/diagnostic'
require_relative 'attractor/pipeline/validator'
require_relative 'attractor/pipeline/context'
require_relative 'attractor/pipeline/outcome'
require_relative 'attractor/pipeline/checkpoint'
require_relative 'attractor/pipeline/artifact_store'
require_relative 'attractor/pipeline/condition_evaluator'
require_relative 'attractor/pipeline/stylesheet'
require_relative 'attractor/pipeline/fidelity_resolver'
require_relative 'attractor/pipeline/session_pool'
require_relative 'attractor/pipeline/transforms/base'
require_relative 'attractor/pipeline/transforms/variable_expansion'
require_relative 'attractor/pipeline/transforms/stylesheet_application'
require_relative 'attractor/pipeline/transforms/preamble'
require_relative 'attractor/pipeline/handlers/base'
require_relative 'attractor/pipeline/handlers/registry'
require_relative 'attractor/pipeline/handlers/start_handler'
require_relative 'attractor/pipeline/handlers/exit_handler'
require_relative 'attractor/pipeline/handlers/codergen_handler'
require_relative 'attractor/pipeline/handlers/wait_human_handler'
require_relative 'attractor/pipeline/handlers/conditional_handler'
require_relative 'attractor/pipeline/handlers/parallel_handler'
require_relative 'attractor/pipeline/handlers/fan_in_handler'
require_relative 'attractor/pipeline/handlers/tool_handler'
require_relative 'attractor/pipeline/handlers/manager_loop_handler'
require_relative 'attractor/pipeline/backends/base'
require_relative 'attractor/pipeline/backends/simulation'
require_relative 'attractor/pipeline/backends/direct_llm'
require_relative 'attractor/pipeline/backends/agent'
require_relative 'attractor/pipeline/interviewer/base'
require_relative 'attractor/pipeline/interviewer/auto_approve'
require_relative 'attractor/pipeline/interviewer/console'
require_relative 'attractor/pipeline/interviewer/callback'
require_relative 'attractor/pipeline/interviewer/queue'
require_relative 'attractor/pipeline/interviewer/recording'
require_relative 'attractor/pipeline/events'
require_relative 'attractor/pipeline/engine'
require_relative 'attractor/pipeline/runner'

module Attractor
end
